version: "2"
services:
    app:
        container_name: app
        build: .
        volumes:
            - ./:/app
        command: npm run install-start    
        ports:
            - "3030:3030"
        environment:
            -  NODE_ENV=${NODE_ENV}
            -  SERVER_PORT=${SERVER_PORT}
            -  SERVER_URL=${SERVER_URL}
