version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: yarn  # install dependencies
      - run:
          name: Run tests
          command: yarn test

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    environment:
      HEROKU_APP: "demoApp"
      HEROKU_API_KEY: HEROKU_API_KEY
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context: demoApp
          requires:
            - build
          filters:
            branches:
              only: master  